// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6BQR8wVCw1zJj6RQ2F3KDrPH0Ynrrb28',
    appId: '1:610890671407:web:c686f41db11935f46a2dda',
    messagingSenderId: '610890671407',
    projectId: 'rasidak-144d9',
    authDomain: 'rasidak-144d9.firebaseapp.com',
    storageBucket: 'rasidak-144d9.firebasestorage.app',
    measurementId: 'G-C2BV17DNYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb7ebdI0wl-0iwot_w5s7tSsVUJ7phZks',
    appId: '1:610890671407:android:1446d30da55cef3f6a2dda',
    messagingSenderId: '610890671407',
    projectId: 'rasidak-144d9',
    storageBucket: 'rasidak-144d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGjMdRZQ1j6xcToP4vh2mdEIHwD3hIIbU',
    appId: '1:610890671407:ios:b65204a33f2cf77d6a2dda',
    messagingSenderId: '610890671407',
    projectId: 'rasidak-144d9',
    storageBucket: 'rasidak-144d9.firebasestorage.app',
    iosBundleId: 'com.example.rasidak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6BQR8wVCw1zJj6RQ2F3KDrPH0Ynrrb28',
    appId: '1:610890671407:web:d243007c137fcd0a6a2dda',
    messagingSenderId: '610890671407',
    projectId: 'rasidak-144d9',
    authDomain: 'rasidak-144d9.firebaseapp.com',
    storageBucket: 'rasidak-144d9.firebasestorage.app',
    measurementId: 'G-GRPVNGCPPP',
  );
}
